version: '2'

networks:
  app-tier:
    driver: bridge
services:
  webs:
    image: docker.io/bitnami/codeigniter:3
    ports:
      - "8000:8000"
    volumes:
      - '.:/app'
    networks:
      - app-tier
    depends_on:
      - mariadb
    environment:
      - CODEIGNITER_PROJECT_NAME=webdev2
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_SKIP_TEST_DB=yes
    networks:
      - app-tier
